# Generated by Django 2.1.8 on 2020-12-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20201229_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
