# Generated by Django 2.1.8 on 2020-12-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20201230_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
